#!/usr/bin/env python


import sys
import argparse
import numpy as np
import pandas as pd


def get_options():
    description = 'Annotate ko scores'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('scores',
                        help='KO scores')
    parser.add_argument('features',
                        help='Reference genome features bed file')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    ffile = options.features
    ifile = options.scores

    f = pd.read_table(ffile,
                      index_col=3,
                      header=None).sort_index()
    fc = f[0].to_dict()
    fp = {x: (y+z)/2 for x, (y, z) in f[[1, 2]].iterrows()}

    m = pd.read_table(ifile)
    m = m.set_index('gene').sort_index()

    m['chrom'] = [fc.get(gene, np.nan)
                  for gene in m.index]
    m['pos'] = [fp.get(gene, np.nan)
                for gene in m.index]
    m = m.reset_index().set_index(['strain',
                                   'condition',
                                   'gene']
        ).sort_index().reset_index()
    m.to_csv(sys.stdout, sep='\t', index=False)
