#!/usr/bin/env python
'''Convert numeral chromosome numbers into roman'''

import sys
import roman
import argparse


def get_options():
    description = 'Convert numeral chromosome numbers into roman'
    parser = argparse.ArgumentParser(description=description)

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    for l in sys.stdin:
        if l.startswith('#'):
            print(l.rstrip())
            continue
        s = l.rstrip().split()
        chr = 'chr' + roman.toRoman(int(s[0].replace('chr', '')))
        s = [chr] + s[1:]
        print('\t'.join(s))
