#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Correlate genes across pairs of strains'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('scores',
                        help='KO scores file')
    
    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import os
    import sys
    import itertools
    import pandas as pd

    m = pd.read_table(options.scores,
                      index_col=[0, 1, 2])['score']
    m = m[~m.index.duplicated()].dropna()
    m = m.reset_index().pivot_table(index=['strain', 'condition'],
                                    columns='gene',
                                    values='score')
    m = m.loc[['YPS', 'Y55', 'UWOP']]
    m = m.corr()
    m.to_csv(sys.stdout, sep='\t')
