#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Correlate genes across pairs of strains'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('scores',
                        help='KO scores file')
    
    parser.add_argument('--out',
                        default='.',
                        help='Output directory [Default: .]')

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import os
    import sys
    import itertools
    import pandas as pd

    m = pd.read_table(options.scores,
                      index_col=[0, 1, 2])['score']
    m = m[~m.index.duplicated()].dropna()
    m = m.reset_index().pivot_table(index='condition',
                                    columns=['strain', 'gene'],
                                    values='score')

    for s1, s2 in itertools.combinations(sorted({x[0]
                                                 for x in m.columns}),
                                         2):
        sys.stderr.write('%s\t%s\n' % (s1, s2))
        x = m[[s1, s2]]
        x = x.corr()
        x.to_csv(os.path.join(options.out, '%s_%s.tsv' % (s1, s2)))
