#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Convert SGD features table into BED'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('sgd',
                        help='SGD features table')

    parser.add_argument('--ncbi',
                        default=None,
                        help='NCBI chromosome ID to SGD')

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    ncbi = {}
    if options.ncbi is not None:
        for l in open(options.ncbi):
            ncbi_id, _, chromosome = l.rstrip().split()
            ncbi[chromosome] = ncbi_id

    for l in open(options.sgd):
        s = l.rstrip().split('\t')
        if len(s) < 11:
            continue
        chrom, start, stop = s[8:11]
        name = s[3]
        if '' in [chrom, start, stop, name]:
            continue
        if int(start) > int(stop):
            tmp = start
            start = stop
            stop = tmp
        try:
            int(chrom)
        except ValueError:
            continue
        if options.ncbi:
            chrom = ncbi.get(chrom, None)
            if chrom is None:
                continue
        print('%s\t%d\t%d\t%s' % (str(chrom),
                                  int(start),
                                  int(stop),
                                  name))
