#!/usr/bin/env python

def get_options():
    import argparse

    description = 'From SGD slim file to GAF'
    parser = argparse.ArgumentParser(description=description)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import sys
    
    d = {}
    for l in sys.stdin:
        s = l.rstrip().split('\t')
        gene, go = s[0], s[5]
        d[gene] = d.get(gene, set())
        d[gene].add(go)

    for gene, gos in d.items():
        print('%s\t%s' % (gene, ';'.join(gos)))
