#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Get the full subset of gene-gene interactions'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('input',
                        nargs='+',
                        help='Input LLR file')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    idx = None
    for f in options.input:
        b = True
        sdx = set()
        for l in open(f):
            if b:
                b = False
                continue
            g1, g2 = l.rstrip().split('\t')[:2]
            sdx.add(tuple(sorted((g1, g2))))
        if idx is None:
            idx = sdx
        else:
            idx = idx.intersection(sdx)

    for g1, g2 in idx:
        print('%s\t%s' % (g1, g2))
